### ISSUE TITLE
python 3 migration

### ISSUE THREAD

**Issue by je-vv** [julian-klode/dir2ogg#9]
dir2ogg is written for python 2.  As python 2 is soon to cease support, it should be migrated to python 3.
If installed as a python 3 sw, just executing `dir2ogg` one gets the following error:
>   File "/usr/bin/dir2ogg", line 145                                                                                                                                      
>     print 'INFO: %s' % msg                                                                                                                                               
>                            ^                                                                                                                                                     
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print('INFO: %s' % msg)?

**Comment by julian-klode** [comment]
Oh wow, yeah that's true.

**Comment by julian-klode** [comment]
Fixed in 0.13
